
name: axe
on: pull_request
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use NodeJS 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm run build --if-present
    - run: npm start & npx wait-on http://localhost:3000
    - name: Run Axe
      run: |
        npm install -g @axe-core/cli
        axe http://localhost:3000 --exit